# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleTextPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='simple_plugins_simpletextpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('flavor', models.PositiveSmallIntegerField(choices=[(1, 'Plain')])),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=80)),
                ('content', djangocms_text_ckeditor.fields.HTMLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TextAndImagePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='simple_plugins_textandimagepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('flavor', models.PositiveSmallIntegerField(choices=[(1, 'Full width with image on the right'), (2, 'Full width with image on the left'), (3, 'One-third width with image between title and content')])),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=80)),
                ('content', djangocms_text_ckeditor.fields.HTMLField()),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
