# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('simple_plugins', '0003_auto_20171222_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleURLTeaserPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='simple_plugins_simpleurlteaserpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('flavor', models.PositiveSmallIntegerField()),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=80)),
                ('content', djangocms_text_ckeditor.fields.HTMLField()),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
