# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('simple_plugins', '0004_simpleurlteaserpluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleurlteaserpluginmodel',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
