# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('simple_plugins', '0005_auto_20180128_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleImagePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='simple_plugins_simpleimagepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('flavor', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=80)),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
